sudo: false
language: ruby
rvm:
  - ruby-head
  - 2.6.0
  - 2.5.0
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10

matrix:
  include:
    # To avoid spamming the travis list with the jdk on each row, we only set it for the jrubies
    - rvm: jruby-head
      jdk: openjdk8
    - rvm: jruby-9.1.9.0
      jdk: openjdk8
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

install:
  - ruby -v
  - gem -v
  - ./bin/setup_bundler_1_17_3_if_needed
  - bundle install
  - rake dev:install
  - npm install -g nyc
script:
  - bundle exec rake test:all
