sudo: false
language: ruby
rvm:
  - ruby-head
  - 2.6.0
  - 2.5.0
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - jruby-head
  - jruby-9.1.9.0

install:
  - gem install bundler
  - rake dev:install
  - npm install -g nyc
script:
  - bundle exec rake test:all
matrix:
  allow_failures:
    - rvm: ruby-head
