sudo: false
language: ruby
rvm:
  #- ruby-head
  #- 2.6.0
  #- 2.5.0
  #- 2.4.1
  #- 2.3.4
  #- 2.2.7
  #- 2.1.10
  #- jruby-head
  #- jruby-9.1.9.0
  - truffleruby

install:
  # The last bundler version that supports our older supported ruby versions is 1.17.3
  # Uninstalling it sometimes gets refused because of default gems, so we ignore the error
  # and hope for the best.
  - gem uninstall bundler -a -x || true
  - rvm @global do gem uninstall bundler -a -x || true
  - gem install bundler -v 1.17.3
  - bundle install
  - rake dev:install
  - npm install -g nyc
script:
  - bundle exec rake test:all
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rmv: truffleruby
